language: ruby

# whitelist
services:  
    #Enable docker service inside travis
    - docker

before_install:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
    #create database and user
    - psql -c 'CREATE DATABASE $DB_NAME' -U postgres
    - psql $DB_NAME --command="CREATE USER "$DB_USER" WITH PASSWORD '"$DB_PSWD"';" -U postgres
    - psql $DB_NAME --command="GRANT ALL PRIVILEGES ON DATABASE "$DB_NAME" TO "$DB_USER";"
    #change postgresql config to work with docker
    - chmod +x database-setup.sh

script:  
    #change postgresql config to work with docker
    - ./database-setup.sh
    #build the image
    - docker build --no-cache -t hipcms/hipcmsrepository .
    #tag the build
    - docker tag hipcms/hipcmsrepository:latest "hipcms/hipcmsrepository:v$TRAVIS_BUILD_NUMBER"
    #push the image to the repository
    - docker push hipcms/hipcmsrepository
    
notifications:
  slack: "$SLACK_SECRET"
