// <auto-generated />
namespace HiP_CmsWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hipcms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hipcms));
        
        string IMigrationMetadata.Id
        {
            get { return "201604101534310_hipcms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
