// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PaderbornUniversity.SILab.Hip.CmsApi.Data;
using System;

namespace PaderbornUniversity.SILab.Hip.CmsApi.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20171030124013_UserStore")]
    partial class UserStore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Icon");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Layer")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("ParentTagId");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<string>("Style");

                    b.HasKey("Id");

                    b.HasIndex("ParentTagId");

                    b.ToTable("AnnotationTags");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DocumentId");

                    b.Property<int>("IdInDocument");

                    b.Property<int>("PositionInDocument");

                    b.Property<int>("TagModelId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TagModelId");

                    b.ToTable("AnnotationTagInstances");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagInstanceRelation", b =>
                {
                    b.Property<int>("SourceTagId");

                    b.Property<int>("TargetTagId");

                    b.Property<string>("ArrowStyle");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<int>("Id");

                    b.Property<string>("Title");

                    b.HasKey("SourceTagId", "TargetTagId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("TargetTagId");

                    b.ToTable("AnnotationTagRelations");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagRelationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArrowStyle");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<int>("SourceTagId");

                    b.Property<int>("TargetTagId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("SourceTagId");

                    b.HasIndex("TargetTagId");

                    b.ToTable("TagRelationRules");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.Layer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Layers");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.LayerRelationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArrowStyle");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<int>("SourceLayerId");

                    b.Property<int>("TargetLayerId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("SourceLayerId");

                    b.HasIndex("TargetLayerId");

                    b.ToTable("LayerRelationRules");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.AssociatedTopic", b =>
                {
                    b.Property<int>("ParentTopicId");

                    b.Property<int>("ChildTopicId");

                    b.HasKey("ParentTopicId", "ChildTopicId");

                    b.HasIndex("ChildTopicId");

                    b.ToTable("AssociatedTopics");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Document", b =>
                {
                    b.Property<int>("TopicId");

                    b.Property<string>("Content")
                        .HasMaxLength(65536);

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdaterId")
                        .IsRequired();

                    b.HasKey("TopicId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TopicId");

                    b.Property<string>("TypeName");

                    b.Property<string>("UpdaterId")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("NotificationId");

                    b.HasIndex("TopicId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.StudentDetails", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrentDegree");

                    b.Property<short>("CurrentSemester");

                    b.Property<string>("Discipline");

                    b.HasKey("UserId");

                    b.ToTable("StudentDetails");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SubscriberId")
                        .IsRequired();

                    b.Property<string>("TypeName");

                    b.HasKey("SubscriptionId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedById")
                        .IsRequired();

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<string>("Requirements");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Path");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("TopicId");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicAttachments");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicAttachmentMetadata", b =>
                {
                    b.Property<int>("TopicAttachmentId");

                    b.Property<string>("Copyright");

                    b.Property<string>("Creator");

                    b.Property<string>("Date");

                    b.Property<string>("Date2");

                    b.Property<int>("Depth");

                    b.Property<string>("DetailedPosition");

                    b.Property<string>("Details");

                    b.Property<int>("Height");

                    b.Property<string>("Location");

                    b.Property<string>("Material");

                    b.Property<int>("Page");

                    b.Property<string>("Photographer");

                    b.Property<string>("PlaceOfManufacture");

                    b.Property<string>("PointOfOrigin");

                    b.Property<string>("Signature");

                    b.Property<string>("Source");

                    b.Property<string>("SubType");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Type");

                    b.Property<string>("Unit");

                    b.Property<int>("Width");

                    b.HasKey("TopicAttachmentId");

                    b.ToTable("TopicAttachmentMetadata");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicReview", b =>
                {
                    b.Property<int>("TopicId");

                    b.Property<string>("ReviewerId");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TopicId", "ReviewerId");

                    b.ToTable("TopicReviews");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicUser", b =>
                {
                    b.Property<int>("TopicId");

                    b.Property<string>("UserId");

                    b.Property<string>("Role");

                    b.HasKey("TopicId", "UserId", "Role");

                    b.ToTable("TopicUsers");
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTag", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTag", "ParentTag")
                        .WithMany("ChildTags")
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagInstance", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Document", "Document")
                        .WithMany("TagsInstances")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTag", "TagModel")
                        .WithMany("TagInstances")
                        .HasForeignKey("TagModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagInstanceRelation", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagInstance", "SourceTag")
                        .WithMany("TagRelations")
                        .HasForeignKey("SourceTagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagInstance", "TargetTag")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetTagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTagRelationRule", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTag", "SourceTag")
                        .WithMany("TagRelationRules")
                        .HasForeignKey("SourceTagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.AnnotationTag", "TargetTag")
                        .WithMany("IncomingTagRelationRules")
                        .HasForeignKey("TargetTagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.LayerRelationRule", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.Layer", "SourceLayer")
                        .WithMany("Relations")
                        .HasForeignKey("SourceLayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Annotation.Layer", "TargetLayer")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetLayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.AssociatedTopic", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", "ChildTopic")
                        .WithMany("ParentTopics")
                        .HasForeignKey("ChildTopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", "ParentTopic")
                        .WithMany("AssociatedTopics")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Document", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", "Topic")
                        .WithOne("Document")
                        .HasForeignKey("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Document", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Notification", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicAttachment", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", "Topic")
                        .WithMany("Attachments")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicAttachmentMetadata", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicAttachment", "TopicAttachment")
                        .WithOne("Metadata")
                        .HasForeignKey("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicAttachmentMetadata", "TopicAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicReview", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", "Topic")
                        .WithMany("Reviews")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.TopicUser", b =>
                {
                    b.HasOne("PaderbornUniversity.SILab.Hip.CmsApi.Models.Entity.Topic", "Topic")
                        .WithMany("TopicUsers")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
